#!/bin/bash
echo "" > log
echo "serial - octave" >> log
echo "vetorial - octave" >> log
echo "multiprocessing - python" >> log
echo "" >> log

for i in {100,500,1000,10000,100000,1000000,10000000}; do 
	echo "$i elementos" >> log
        /usr/bin/time -a -o log -f "%E" octave leibniz_sequencial.m $i
        /usr/bin/time -a -o log -f "%E" octave leibniz_vetorial.m $i
        /usr/bin/time -a -o log -f "%E" python3 leibniz_numpy.py $i
        echo "" >> log
done
